# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieInfo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieInfo
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'

# RxTest and RxBlocking make the most sense in the context of unit/integration tests
target 'MovieInfoTests' do
    pod 'RxBlocking'
    pod 'RxTest'
end

end
